### ISSUE TITLE
Issue loading pre-computed MCMC chains into MCMC_Output

### ISSUE THREAD

**Issue by dvzhukov** [catavallejos/BASiCS#10]
Running BASiCS on R-3.3.2. Using the following code from the BASiCSIntro vignette:

`ChainMu = as.matrix(read.table("chain_mu_Test.txt"))`
`ChainDelta = as.matrix(read.table("chain_delta_Test.txt"))`
`ChainPhi = as.matrix(read.table("chain_phi_Test.txt"))`
`ChainS = as.matrix(read.table("chain_s_Test.txt"))`
`ChainNu = as.matrix(read.table("chain_nu_Test.txt"))`
`ChainTheta = read.table("chain_theta_Test.txt")[,1]`

`MCMC_Output <- newBASiCS_Chain(mu = ChainMu, delta = ChainDelta, phi = ChainPhi, 
                               s = ChainS, nu = ChainNu, theta = ChainTheta)`

I'm receiving the following error:

`Error in validObject(.Object) : invalid class “BASiCS_Chain” object: invalid object for slot "theta" in class "BASiCS_Chain": got class "factor", should be or extend class "matrix"`

It appears that `newBASiCS_Chain` expects `theta` to be of class "matrix". Trying

`ChainTheta = as.matrix(read.table("chain_theta_Test.txt")[,1])`
and
`ChainTheta = as.matrix(read.table("chain_theta_Test.txt"))`

also to no avail, producing a different error:

`Error in validObject(.Object) : invalid class “BASiCS_Chain” object: One or more of the slots contains NAs or Infinite values`

Any input would be greatly appreciated!

**Comment by catavallejos** [comment]
Could you please print `head(ChainTheta)` in the console? 

My guess is that something went wrong when storing that file.

**Comment by catavallejos** [comment]
Also, I recently added a new function to facilitate the process of loading the chains (it's not yet updated in the vignette). You can try it our using

`BASiCS_LoadChain(RunName = "Test", StoreDir = getwd(), WithSpikes = TRUE)`

You must replace `getwd()` by the directory where your chains are stored. 

Let me know how it goes!

**Comment by dvzhukov** [comment]
I think storing the file is not the issue:

`> head(ChainTheta)`
`     V1                 `
`[1,] "Batch1"           `
`[2,] "0.172701505484893"`
`[3,] "0.250710435515433"`
`[4,] "0.311919500415724"`
`[5,] "0.661582888720355"`
`[6,] "0.479110944221807"`

However, using `BASiCS_LoadChain(RunName = "Test", StoreDir = getwd(), WithSpikes = TRUE)` totally fixed the issue!

Thank you for the quick response!
