### ISSUE TITLE
calculating residual over-dispersion per individual sample

### ISSUE THREAD

**Issue by ndsimons** [catavallejos/BASiCS#114]
Hi Catalina, 

I have a question about the possible use of BASiCS to generate residual over-dispersion estimates for individual samples. 

My data consists of 10 individuals, each with ~7k genes ~200 cells. Half of the samples each belong to one of two groups, and I've used BASiCS with no spikes and regression=TRUE previously to analyze the data as BASiCS is intended, at the group level. 

I'd like to generate individual-level estimates (as opposed to group-level) of residual over-dispersion to use in some mixed-effects models. In principle I'd like to generate an MCMC chain for individual 1 and another for individual 2 and then do BASiCS_TestDE and extract the ResDisp1 and ResDisp2 (and so on for each of the individuals) from the TableResDisp.

The problem is that when generating a chain for a set of cells from a single individual, there is no batch. Any suggestions on how I might generate these individual-level residual over-dispersion estimates?

Thanks very much!
Noah

**Comment by Alanocallaghan** [comment]
Hi @ndsimons. 

In principle the model can work without batches in the no spikes case though (as far as I know) we haven't formally tested whether it works well in practice. 

If you want to test it, the only obstacles are two error conditions [here](https://github.com/catavallejos/BASiCS/blob/master/R/HiddenBASiCS_MCMC_InputCheck.R#L39) and [here](https://github.com/catavallejos/BASiCS/blob/master/R/HiddenChecksBASiCS_Data.R#L60).

I've commented these out in the `nobatch` branch, which is based on the `Devel` branch. That should let you run the model without spikes or batches. If you want to be more conservative, then please comment those warnings out on a branch based on master yourself.

If you test it out let me know if you run into any oddities or difficulties. I'm currently working on similar data myself.

btw - is this data of a single cell type? ie, is there substantial hetereogeneity in the data. If so, the model will likely struggle to find real signal in this case.

**Comment by ndsimons** [comment]
Hi Alan, 

Fantastic, thanks so much for looking into this! So I forked the BASiCS repository, commented out the two sections you referenced, and re-installed the forked version. 

Both `BASiCS_MCMC` and `BASiCS_TestDE` seem to be working 

So, the data are from a single cell type, should I still just assess chain convergence and acceptance rates as prescribed in the vignette?

**Comment by Alanocallaghan** [comment]
Yep, you can check out the diagHist/diagPlot functions to check that you have a reasonable effective samples, and of course look at some of the trace plots. I would probably sanity check the results a bit before running higher level analyses as well - perhaps see what happens if you run 1 or 2 samples together with "sample" as batch versus the samples run separately.

**Comment by Alanocallaghan** [comment]
I'll close this, but if you have any further questions or comments about this please do get in touch!
