### ISSUE TITLE
dividing by zeors in "BASiCS_Filter" function

### ISSUE THREAD

**Issue by xuchang116** [catavallejos/BASiCS#13]
Hello Catalina, 

I encountered an error in "BASiCS_Filter" function which I believe was rooted in the line 

IncludeBio = ifelse(apply(Counts1[!Tech, ], 1, sum)/apply(NonZero[!Tech,], 1, sum) >= MinAvCountsPerCellsWithExpression, IncludeBio, F)

The problem is if a gene has 0 counts in all cells, apply(NonZero[!Tech,], 1, sum) gives 0 for that gene. As a result, the condition being evaluated in the 'ifelse' becomes NaN. So IncludeBio has some NA values. The final error message is

Error in newBASiCS_Data(Counts = Filter$Counts, Tech = Filter$Tech, SpikeInfo = SpikeInfoFilter) :
  SpikeInfo is missing information for some of the spikes

Could you check on this? Thank you! 

Chang

**Comment by catavallejos** [comment]
Dear Chang,

My apologies for the delayed response but your email found me travelling.

I modified the 'BASiCS_Filter' function to avoid this issue. Please let me know if you still have the problem for your data.

Best

Catalina
