### ISSUE TITLE
Error: object 'cv2Bio2' not found

### ISSUE THREAD

**Issue by bdulken** [catavallejos/BASiCS#14]
Thank you for this fantastic package!

I am trying to implement it and having a little bit of trouble.

When I run BASiCS_MCMC() I get the following error:
Error in HiddenBASiCS_MCMC_Start(Data) : object 'cv2Bio2' not found

My call to BASiCS_MCMC() is as follows:
> MCMC_OutputTest <- BASiCS_MCMC(Data.old, N = N, Thin = Thin, Burn = Burn,
+                                PrintProgress = TRUE, StoreChains = FALSE,
+                                StoreDir = chains.path, RunName = RunName.old)

Thank you for any insight you can provide!
-Ben

**Comment by catavallejos** [comment]
Hi Ben, 

I glad to hear you like the package :)

I am sorry for this error. It was a typo left after our last update. It should be fixed now. 

Let me know if you find any other issues!

Best

Cata
