### ISSUE TITLE
Fix Bioc 3.11 (devel) branch

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#142]
Message from Bioc Core team

> We would like to make you aware your package is currently failing across all three platforms in Bioconductor devel 3.11.  This looks like it has to do with a function change from scran on calculateSumFactors.  Please investigate to avoid package deprecation.

**Comment by Alanocallaghan** [comment]
957d18518c1abb81944d2f929da496940c7d9a0d
