### ISSUE TITLE
Can't supply just some of PriorParam/Start

### ISSUE THREAD

**Issue by Alanocallaghan** [catavallejos/BASiCS#154]

**Comment by Alanocallaghan** [comment]
PriorParam should be a function with default args

**Comment by lilythepooh** [comment]
Sorry, does this mean that PriorParam like s2.delta can no longer be changed? We used to be able to do things like BASiCS_MCMC(data,..., s2.delta=2, a.theta=3), but in the newest version, it will return an error if we try to do so.

**Comment by catavallejos** [comment]
Hi @lilythepooh. Thanks for contacting us. Apologies, the number of hyper parameters to be passed via `PriorParam` is now larger and I believe that's what might cause the error. Could you please tell us what's is the error message you get?

We will to resolve this asap.

Best wishes

Catalina

**Comment by Alanocallaghan** [comment]
I think the current default PriorParams are:
```
PriorParam = list(
      mu.mu = 0,
      s2.mu = 0.5,
      s2.delta = 0.5,
      a.delta = 1, 
      b.delta = 1,
      p.phi = rep(1, times = ncol(d)),
      a.s = 1,
      b.s = 1,
      a.theta = 1,
      b.theta = 1,
      m = numeric(k),
      V = diag(k),
      a.sigma2 = 2,
      b.sigma2 = 2,
      GeneExponent = 1,
      CellExponent = 1,
      eta = 5
    )
```

Notice the new `*Exponent` arguments. We'll be adding a function to make this easier to specify soon.

**Comment by lilythepooh** [comment]
Hello @catavallejos Thanks so much for your early reply. After running BASiCS_MCMC(data, N=20000, Thin=10, Burn=10000, Regression=TRUE, PrintProgress=T, s2.delta=2), I get the error message I get is "Error in HiddenBASiCS_MCMC_ExtraArgs(Data, Burn, GPar, Regression, WithSpikes, : unused argument (s2.delta=2)". This is the first time that I am using BASiCS version 1.8.1 after upgrading to R 3.6.1. Before this, I was using BASiCS version 1.4.7 in R 3.5.3. 
I am wondering if we should change hyperparameters by giving "BASiCS_MCMC(data,...,PriorParam=list(mu.mu=0,...,s2.delta=2,...)) now?
Thanks for your time:-)

**Comment by Alanocallaghan** [comment]
This call should work in the current BASiCS:

```
BASiCS_MCMC(d, N=20000, Thin = 10, Burn = 10000, Regression = TRUE, WithSpikes = TRUE,
  PriorParam = list(
      mu.mu = 0,
      s2.mu = 0.5,
      s2.delta = 0.5,
      a.delta = 1, 
      b.delta = 1,
      p.phi = rep(1, times = ncol(d)),
      a.s = 1,
      b.s = 1,
      a.theta = 1,
      b.theta = 1,
      m = numeric(k),
      V = diag(k),
      a.sigma2 = 2,
      b.sigma2 = 2,
      GeneExponent = 1,
      CellExponent = 1,
      eta = 5
  )
)
```

**Comment by lilythepooh** [comment]
@Alanocallaghan Thanks so much for the information! Have a nice weekend.

**Comment by lilythepooh** [comment]
@Alanocallaghan Sorry, is the "k" in "m = numeric(k), V = diag(k)" the number of regression Gaussian Radial Basis Functions (GRBF) used within the correlated prior adopted for gene-specific over-dispersion and mean expression parameters? After I input BASiCS_MCMC(data=,...,PriorParam=list(...,m=numeric(k), V=diag(k))), I got the Error "object 'k' not found". I thought "k" has a default value 12, or shall I specify it somewhere?

**Comment by Alanocallaghan** [comment]
Sorry you're correct - I checked the code before sending but I must have had `k` defined already. The default value of k is currently 12.

```r 
k <- 12
BASiCS_MCMC(Data, 
  N=20000, Thin = 10, Burn = 10000, Regression = TRUE, WithSpikes = TRUE,
  PriorParam = list(
      mu.mu = 0,
      s2.mu = 0.5,
      s2.delta = 0.5,
      a.delta = 1, 
      b.delta = 1,
      p.phi = rep(1, times = ncol(d)),
      a.s = 1,
      b.s = 1,
      a.theta = 1,
      b.theta = 1,
      m = numeric(k),
      V = diag(k),
      a.sigma2 = 2,
      b.sigma2 = 2,
      GeneExponent = 1,
      CellExponent = 1,
      eta = 5
  )
)
```
