### ISSUE TITLE
Can we store ESS within BASiCS_Chain objects?

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#178]
Not efficient to re-calculate whenever it's needed

**Comment by Alanocallaghan** [comment]
Yeah I think we discussed storing it as an extra element of the list, I guess the idea got lost along the way. There's workarounds in a few places because the assumption is that everything stored in parameters is a matrix with nSamples rows.

**Comment by catavallejos** [comment]
Yes, I remember discussing this at some point but we didn't follow up. For the next release :-)

**Comment by catavallejos** [comment]
Maybe it could go in BASiCS_Summary?

**Comment by catavallejos** [comment]
Maybe an alternative is to include an optional `ESS` parameter in `BASiCS_DiagPlot`? If `ESS = NULL`, then ESS is calculated. If not, user-provided values are used.

**Comment by Alanocallaghan** [comment]
I think it's better to store in the objects, can just calculate it for the parameters when chain finished

**Comment by catavallejos** [comment]
[Here](https://jrnold.github.io/bayesian_notes/mcmc-diagnostics.html) is an alternative formula to calculate ESS:

```
ess <- function(x) {
  N <- length(x)
  V <- map_dbl(seq_len(N - 1),
          function(t) {
             mean(diff(x, lag = t) ^ 2, na.rm = TRUE)
          })
  rho <- head_while(1 - V / var(x), ~ . > 0)
  N / (1 + sum(rho))
}
```
I have not compared its output with what is obtained by `coda`, but worth checking in case it's faster.

**Comment by Alanocallaghan** [comment]
Our implementation (coda one with some stuff stripped out) is much faster (>1 order of magnitude)
```
microbenchmark(ess(m), ess2(m))
Unit: milliseconds
    expr        min        lq       mean     median         uq        max neval
  ess(m)   4.759473   4.82852   5.115822   4.980513   5.085284   8.973209   100
 ess2(m) 225.016671 228.36865 234.330501 230.711017 235.311487 257.537234   100
```
ess is ours, ess2 is that one

**Comment by Alanocallaghan** [comment]
Could store ESS as an attribute of each parameter matrix, then we don't need to change anything

**Comment by Alanocallaghan** [comment]
Need to handle the case that ESS fails for some reason!
