### ISSUE TITLE
Update Wiki to match current UI?

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#180]
Do we need the wiki? Workflow/vignette may be enough, but wiki provides quick links.

**Comment by Alanocallaghan** [comment]
I think having links and extra material on the wiki (eg troubleshooting) is good but having code on there is risky. The advantage of vignettes is they are checked automatically, meaning that the code and output are more likely to be valid. Wikis have a bad habit of drifting out of date

**Comment by catavallejos** [comment]
Added warning to wiki to indicated that is no longer maintained and that vignette must be used instead.
