### ISSUE TITLE
BASiCS_DenoisedCounts

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#182]
- Option to exclude spike-ins
- Replace median(phi) * median (nu) by median(phi * nu) -> not significantly different, but second is more principle.

**Comment by Alanocallaghan** [comment]
I was fully ready to replace a lot of `t(t(mat) / vec)` with `sweep(mat, 2, vec, "/")` but apparently the double transpose is faster? R never fails to impress
