### ISSUE TITLE
Use bayefdr

### ISSUE THREAD

**Issue by alanocallaghan** [catavallejos/BASiCS#184]
There are 2 edge cases that the package doesn't cover but otherwise should be fine to mostly just remove the code and replace with calls. Once I've changed I'll push to CRAN

**Comment by Alanocallaghan** [comment]
This simplifies the Result classes since they can just store the bayefdr object.

**Comment by Alanocallaghan** [comment]
This is slightly more complex than I thought. We don't currently store the probability thresholds that we check for EFDR/EFNR (that seems very wrong to me)
