### ISSUE TITLE
Bugs in BASiCS_DetectVG

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#188]
- Default setting uses `ProbThreshold = 0.5` and therefore EFDR calibration is ignored.
- We should use `ProbThreshold = NULL` as default? 
- If `ProbThreshold = NULL`, an error is currently eturned:

`Error in if (ProbThresholds[optimal] >= ProbThreshold) { : 
  argument is of length zero`

**Comment by catavallejos** [comment]
To-do list:

- [x] Change treatment of `ProbThreshold` and `EFDR` as in `BASiCS_TestDE`
-

**Comment by Alanocallaghan** [comment]
> Removes Threshold from the output provided by BASiCS_DetectVG. Is this OK? Note that use didn't seem to be consistent. Threshold = ProbTreshold if regression, Threshold = VarThreshold otherwise.

I don't think this is a good idea, the threshold used to categorise the genes (regardless of method) seems like important information

**Comment by Alanocallaghan** [comment]
Also #184, can standardise the handling of efdr a bit

**Comment by catavallejos** [comment]
Good point! I will finish with the current changes, but we can move to use the efdr library instead

**Comment by catavallejos** [comment]
Closing this issue and moving remaining items to #192 and #193.

**Comment by catavallejos** [comment]
All changes merged by PR https://github.com/catavallejos/BASiCS/pull/194
