### ISSUE TITLE
setGeneric for format?

### ISSUE THREAD

**Issue by Alanocallaghan** [catavallejos/BASiCS#189]
So setMethod should implicitly call setGeneric  but something's gone wrong. Maybe an upstream package has removed it.

Somewhat conflicting advice from eg https://thomas-cokelaer.info/blog/2013/01/r-language-object-oriented-programming/, https://stat.ethz.ch/R-manual/R-devel/library/methods/html/setGeneric.html about setGeneric's safety. The latter says that multiple generics are identical and just added to a methods table.

For now going with setGeneric but this may cause issues!

**Comment by catavallejos** [comment]
one option is to request `format` to be added to `BiocGenerics`. Not sure what are the rules for that.

**Comment by Alanocallaghan** [comment]
Deprecating it
