### ISSUE TITLE
 Revise default behaviour for .ThresholdSearch

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#192]
**Should default value for `ProbThreshold` be 2/3 whenever the calibration fails or the threshold is too low?** 🔴 

```
  # 1. If EFDR is provided - run calibration
  #   1.1. If the calibration doesn't completely fail - search prob
  #     1.1.1. If optimal prob is not too low - set prob to optimal
  #     1.1.2. If optimal prob is too low - fix to input ProbThreshold
  #   1.2 If calibration completely fails - default prob to 0.9 (conservative)
  # 2. If EFDR is not provided - fix to input ProbThreshold
```

**Comment by Alanocallaghan** [comment]
The idea is to make the threshold returned in condition 1.2 identical to that returned in condition 1.1.2 and condition 2?

**Comment by catavallejos** [comment]
Yes, that's what I had in mind.

**Comment by catavallejos** [comment]
That will also provide users with the ability to modify the threshold (via `ProbThreshold`) whenever the EFDR calibration fails. Currently, 0.9 is a hard default.

**Comment by Alanocallaghan** [comment]
Yeah I think they should match, it's not clear to me why 1.1.2 and 1.2 need different treatment

**Comment by catavallejos** [comment]
indeed! this seems to be a legacy from old times :-)

**Comment by catavallejos** [comment]
I will add this as a final change in the lvg_hvg_fixes branch and set a PR to merge with master

**Comment by catavallejos** [comment]
Closed by https://github.com/catavallejos/BASiCS/pull/194
