### ISSUE TITLE
HVG/LVG add option to set up threshold directly on epsilon, rather than percentile?

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#193]

**Comment by catavallejos** [comment]
I really think we should do this. The interpretation would be similar to what is implemented in scran. 

For example, if the epsilon threshold is equal to $\log(2)$, HVG would be those genes 
for which the inferred over-dispersion is at least $2$ times higher than
would be expected for associated mean expression level.

**Comment by Alanocallaghan** [comment]
I also think it's a good idea, though I don't think log scale is required here? Since it's already a regression of log(delta) vs log(mu)

**Comment by catavallejos** [comment]
Indeed, the threshold is already in log-scale. The log(2), was just to match a 2-fold excess of over-dispersion

log(delta) = log(f(mu)) + log(2) -> delta = f(mu) * 2

**Comment by Alanocallaghan** [comment]
Excellent point, serves me right for trying to do the rearrangement mentally :)
