### ISSUE TITLE
BASiCSIntro Vignette results in incorrect dimensions error

### ISSUE THREAD

**Issue by jenzopr** [catavallejos/BASiCS#2]
Dear Catalina,

I'm trying to a) reproduce your code in the vignette and then b) apply BASiCS to a scRNA-Seq data set from our group. Unfortunately, when using the example code provided in the BASiCSIntro, I get an "Error in SpikeInfo[,1]: incorrect number of dimensions". 

The code used is
```R
>set.seed(1)
>Counts = Counts = matrix(rpois(50*10, 2), ncol = 10)
>Tech = c(rep(FALSE,40),rep(TRUE,10))
>set.seed(2)
>SpikeInput = rgamma(10,1,1)
>
# No batch effect
>DataExample = newBASiCS_Data(Counts, Tech, SpikeInput)
Error in SpikeInfo[, 1] : incorrect number of dimensions
```

Best,
Jens

**Comment by jenzopr** [comment]
I tried to figure out by myself. It seems that the SpikeInput parameter requires a vector for BASiCS_Data_Class, but a data.frame with two columns when used in newBASiCS_Data() from FunctionsPart1.R

Best, Jens

**Comment by catavallejos** [comment]
Dear Jens,

My apologies for the late reply. I also notice the same issue while testing an updated version of the library. The current version includes an updated version of the vignette file. 

Please do not hesitate to ask if you have any issue. 

Best wishes,

Cata

**Comment by jenzopr** [comment]
Thanks a lot :)
