### ISSUE TITLE
BASiCS_MCMC: creation of the output object fails when delta contains NA

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#211]
... which is now always the case for genes expressed in less than 3 cells.

**Comment by catavallejos** [comment]
Fix line 122 in `AllClasses.R`. Replace

```
      object@parameters[names(object@parameters) != "epsilon"],
```

by

```
      object@parameters[!(names(object@parameters) %in% c("epsilon", "delta"))],
```

**Comment by Alanocallaghan** [comment]
Yeah I came across this already, I believe it's fixed  in the prs

**Comment by catavallejos** [comment]
thanks. let me know when the PRs are ready to be merged

On 6 Oct 2020, at 10:02, Alanocallaghan <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah I came across this already, I believe it's fixed in the prs

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by Alanocallaghan** [comment]
I'm at a bit of a loss atm with the osx failures but I'll try to remote debug

**Comment by Alanocallaghan** [comment]
I'm at a bit of a loss atm with the osx failures but I'll try to remote debug

**Comment by Alanocallaghan** [comment]
It's failing on master but bioc checks pass, might be worth chancing it and pushing to bioc  #212

**Comment by Alanocallaghan** [comment]
I'll double check them and ping you

**Comment by Alanocallaghan** [comment]
I'll double check them and ping you

**Comment by alanocallaghan** [comment]
Should be fixed now
