### ISSUE TITLE
Parameter values used for GRBF functions?

### ISSUE THREAD

**Issue by lilythepooh** [catavallejos/BASiCS#217]
Hello,

I am trying to simulate data from this model for some test. Could you please tell me the value of L, m_l and h_l used when you are calculating the GRBF for delta?

Thank you so much!

**Comment by Alanocallaghan** [comment]
The default parameters are L=10 which implies 10 RBFs, an intercept and a linear term. h_l is set to 1.2 by default. In the original implementation described in the Cell paper the m_l are set to a uniform grid from `min(log(mu))` to `max(log(mu))`. This is still the case by default

There is now a flag that controls whether RBFs are placed at the extrema of `log(mu)`, see:
https://github.com/catavallejos/BASiCS/blob/effdd004f5467306873793cedf753b14e25a206a/src/updatesReg.h#L31
This option may stabilise inference at the extremes when fewer genes are available

To demonstrate:
``` r
library("BASiCS")
set.seed(42)
mu <- rlnorm(100)
## old way of calculating m_l
locs1 <- BASiCS:::.estimateRBFLocations(log(mu), 12, TRUE)
## new optional way
locs2 <- BASiCS:::.estimateRBFLocations(log(mu), 12, FALSE)
plot(log(mu))
abline(h = locs1, col = "blue")
```

![](https://i.imgur.com/BwSWPqP.png)

``` r
plot(log(mu))
abline(h = locs2, col = "red")
```

![](https://i.imgur.com/XbVjxUD.png)

**Comment by Alanocallaghan** [comment]
Let me know if you need more information to run these simulations

**Comment by lilythepooh** [comment]
Dear Alan, Thanks so much for your detailed information. Have a good evening! Best wishes,Sijia Li From: AlanocallaghanSent: 16 November 2020 13:44To: catavallejos/BASiCSCc: Sijia Li; AuthorSubject: Re: [catavallejos/BASiCS] Parameter values used for GRBF functions? (#217) The default parameters are L=10 which implies 10 RBFs, an intercept and a linear term. h_l is set to 1.2 by default. In the original implementation described in the Cell paper the m_l are set to a uniform grid from min(log(mu)) to max(log(mu)). This is still the case by defaultThere is now a flag that controls whether RBFs are placed at the extrema of log(mu), see:https://github.com/catavallejos/BASiCS/blob/effdd004f5467306873793cedf753b14e25a206a/src/updatesReg.h#L31This option may stabilise inference at the extremes when fewer genes are availableTo demonstrate:library("BASiCS")set.seed(42)mu <- rlnorm(100)## old way of calculating m_llocs1 <- BASiCS:::.estimateRBFLocations(log(mu), 12, TRUE)## new optional waylocs2 <- BASiCS:::.estimateRBFLocations(log(mu), 12, FALSE)plot(log(mu))abline(h = locs1, col = "blue")plot(log(mu))abline(h = locs2, col = "red")—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
