### ISSUE TITLE
Differential varibility test when the residual over-dispersion calculated for the two groups toghather.

### ISSUE THREAD

**Issue by almog5690** [catavallejos/BASiCS#229]
Hello,
I'm trying to perform a differential variability test between 24-month-old mice and 3-month-old mice.
My problem is when I'm creating the Markov chain (with BASiCS_MCMC) of the two age groups the Mean-Over-dispersion trend and the Residual over-dispersion are calculated for each group individually. 
Is there a way to calculate the Mean-Over-dispersion trend and the Residual over-dispersion for both age groups together and then performing the differential variability test (using BASiCS_TestDE) for the two groups?

**Comment by Alanocallaghan** [comment]
Hi Almog, as we discussed by email at the moment there is not a way to share the trend between groups. However it's likely that adjusting for the technical effects in each group separately as is done in the 2018 Cell paper doesn't generally present issues
