### ISSUE TITLE
Processing raw data with CellBender prior to BASiCS analysis

### ISSUE THREAD

**Issue by binyaminZ** [catavallejos/BASiCS#233]
Hi, (this is not a technical issue rather a usage consultation...)
I saw a few recent studies (like [this](https://www.nature.com/articles/s41586-021-03570-8/figures/5)) that perform ambient RNA background removal with [CellBender](https://cellbender.readthedocs.io/en/latest/introduction/index.html#introduction) prior to their analysis and see substantial improvement in quantification quality. If I understand correctly, your model doesn't account for this type of noise, which is assumed to be global (not cell-specific) and uniform (unlike the "unexplained noise" component in your model). CellBender also deals with barcode swapping.
This is particularly important when dealing with _single-nucleus_ RNAseq data, as in the study mentioned above and in my case. Do you think it would be beneficial to run CellBender prior to BASiCS? Or it might introduce some bias that could interfere with correct BASiCS performance? 
Thanks,
Binyamin

**Comment by Alanocallaghan** [comment]
Hi Binyamin,

I haven't read the CellBender paper in detail, but I don't think there would be any issues using BASiCS on the corrected count matrix that it creates. As you say it should handle extra noise sources that BASiCS doesn't account for, so it seems like a good idea in principle. If you do use it feel free to post any issues or feedback that result from it
Cheers
Alan
