### ISSUE TITLE
logit transform volcano plots?

### ISSUE THREAD

**Issue by alanocallaghan** [catavallejos/BASiCS#241]
From workflow reviews. I think it looks better, although I see two issues:

1. Picking breaks. By default I've gone with 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99, but this is arbitrary. Probably a great default, but we may want to be smarter at some point. Having said that, users can always xlim them afterwards if they really want to.
2. Any values exactly 0 or 1 are -Inf, Inf. To counteract this I've used a nudge function that sets these to the second-lowest value minus a bit (or the second-highest plus a bit). Means you don't get points way out in the distance distorting the range, but it is somewhat "dishonest".

Example plots from the workflow
- without logit:
![nologit](https://user-images.githubusercontent.com/10779688/179749396-f3564c1e-4821-4f8f-90ee-4311ea896611.png)
- with logit:
![logit](https://user-images.githubusercontent.com/10779688/179749400-712654e5-4790-4579-9e25-fc1d1eee076b.png)

**Comment by Alanocallaghan** [comment]
Ah, looks like some points are being removed from the overdisp/resdisp panels in the logit example. Will investigate

**Comment by Alanocallaghan** [comment]
See branch [logit-scale](https://github.com/catavallejos/BASiCS/compare/logit-scale?expand=1)
