### ISSUE TITLE
HVG and LVG tables have mu values duplicated in the delta column

### ISSUE THREAD

**Issue by binyaminZ** [catavallejos/BASiCS#265]
after running `BASiCS_DetectHVG` and `BASiCS_DetectLVG` i get tables (with `as.data.frame`) that look like:
```
GeneName GeneIndex          Mu       Delta   Epsilon  Prob  HVG
1      aip-1       319 17.19351625 17.19351625 1.8489480 1.000 TRUE
2      atp-6         5  2.61723085  2.61723085 2.5164556 1.000 TRUE
3    C12D5.3       270  0.12569565  0.12569565 1.3859809 0.918 TRUE
```
I noted that Mu and Delta columns are the same, after checking the chain summaries I see these are the mu values, while delta values are missing.
Here is my code for loading the chains:
```
MCMC_chain = BASiCS_LoadChain("my_chain")
HVG <- as.data.frame(BASiCS_DetectHVG(MCMC_chain, PercentileThreshold = 0.8))
LVG <- as.data.frame(BASiCS_DetectLVG(MCMC_chain, PercentileThreshold = 0.2))
```
Any clue? or is it a bug?
Thanks!
(Using `BASiCS_2.7.5`)

**Comment by Alanocallaghan** [comment]
Yep that's a bug, should be fixed now in Bioc release or devel, or on github master

**Comment by catavallejos** [comment]
thanks @Alanocallaghan !
