### ISSUE TITLE
newBASiCS_Data still requires a Tech argument even if no spike-ins are used

### ISSUE THREAD

**Issue by Cumol** [catavallejos/BASiCS#27]
`basics.data <- newBASiCS_Data(round(counts(filter.sce)), BatchInfo = labels$AnimalAmpBatch)`

produced the error:

`Error in !Tech : invalid argument type`

Adding a Tech object with the following:

`Tech <- vector(mode = "logical",length = length(filter.sce))`

solves the issue.

**Comment by BrainStuck** [comment]
I'm also facing this issue.
After adding a Tech object, it's still requiring a SpikeInfo argument:
`Error in newBASiCS_Data(Counts = counts(sce2_qc), BatchInfo <- as.factor(sce2_qc$group),  : 
  'SpikeInfo' must be a 'data.frame'`
And I tried to add an empty data frame
`SpikeInfo = data.frame()`
But it still has error.
```Error in `[.data.frame`(SpikeInfo, , 1) : undefined columns selected```

**Comment by BrainStuck** [comment]
I met a similar problem
```
Data = makeExampleBASiCS_Data(WithSpike = FALSE)
```
produced the error
```
Error in newBASiCS_Data(Counts = Counts.sim, Tech = rep(FALSE, q.bio),  : 
  'SpikeInfo' must be a 'data.frame'
```

**Comment by catavallejos** [comment]
@Cumol thank you for point this out! This should be resolved in [BASiCS v 1.1.36](https://github.com/catavallejos/BASiCS/commit/f493138ac4251cf29230a71829b79969d96685c4)

**Comment by catavallejos** [comment]
@BrainStuck what version of BASiCS are you using? I can replicate the error you mentioned regarding `makeExampleBASiCS_Data`.

**Comment by BrainStuck** [comment]
@catavallejos it was in version 1.0.0

**Comment by catavallejos** [comment]
@BrainStuck thanks. Version 1.0.0 does not support the no-spike case. If you want to use the not spikes case, you need to use the devel version of BASiCS:

```
source("https://bioconductor.org/biocLite.R")
useDevel()
biocLite("BASiCS")
```

Note: I just pushed the latest commit to BioC devel, it should be available there tomorrow.

**Comment by catavallejos** [comment]
Closing this issue for now. Please re-open if needed.
