### ISSUE TITLE
R version requirement resulting in installation failure

### ISSUE THREAD

**Issue by BrainStuck** [catavallejos/BASiCS#28]
I tried to install via GitHub `devtools::install_github("catavallejos/BASiCS", build_vignettes = TRUE)` 
but it failed with an weird error:
`ERROR: this R is version 3.4.3, package 'BASiCS' requires R >= 3.5`
The latest version of R is 3.4.3
Installation via Bioconductor doesn't have this problem.

**Comment by Cumol** [comment]
@BrainStuck actually this error is telling you to install the development version of R which is 3.5.

For example, for MaxOS you can find the binaries here:

https://r.research.att.com/

This is like a complete additional installation of R so you will have to re-install all the packages you need and some of them will not work right away.

**Comment by catavallejos** [comment]
@Cumol : Thanks for answering this issue! (I was away while it was raised)

@BrainStuck : I just have one comment to add. The current version of BASiCS that is available in this repository is our development branch. At times, this can be unstable (particularly when we are working on new improvements). If you want to use our development branch, I recommend you to download it from the devel branch of Bioconductor instead.
