### ISSUE TITLE
(1) Extend vignette with clearer explanation how to run the non-spike case

### ISSUE THREAD

**Issue by nilseling** [catavallejos/BASiCS#30]
Ideally show how to set up the Data object when spikes are not present

**Comment by joefarned** [comment]
Hi Nils, 

I just started playing around with a dataset today that does not contain spike-in genes and I've come across this issue. Any quick pointers on what do pass to newBASiCS_Data() for spike_info?

Thanks!

**Comment by joefarned** [comment]
Looking at the release 3.6 version of the function, SpikeInfo must be a data.frame or the function will return, so is.null(SpikeInfo) will always be false (at line 66). Is my diagnosis correct?

I also see that the development version deals with this issue pretty explicitly. Would you recommend just using the development version? Thanks!

**Comment by nilseling** [comment]
Hi Joe,

I added more info to the vignette on how to construct the BASiCS_Data object when no spike-ins are available. 

Here is an example on how to run the non-spike case.

DataNoSpikes <- newBASiCS_Data(Counts, Tech, SpikeInfo = NULL, 
                              BatchInfo = BatchInfo)
ChainNoSpikes <- BASiCS_MCMC(Data = DataNoSpikes, N = 1000, 
                             Thin = 10, Burn = 500, 
                             WithSpikes = FALSE, 
                             PrintProgress = FALSE)

Best,

Nils

**Comment by joefarned** [comment]
Hi Cata, 

Thanks for the quick reply! I'll work from BioC devel and keep you posted of any issues I come across.

Best,
Joe

**Comment by joefarned** [comment]
And thanks Nils! I'll give it a shot.

**Comment by catavallejos** [comment]
Also edit vignette to clarify the use of `Regression = TRUE` as a preferred option

**Comment by catavallejos** [comment]
Vignette has been updated. See commit [10b21dd](https://github.com/catavallejos/BASiCS/commit/10b21dd7be713c94c271ddcb22e00bddfcfe0f56)
