### ISSUE TITLE
Data = makeExampleBASiCS_Data(WithBatch = FALSE)

### ISSUE THREAD

**Issue by Horta** [catavallejos/BASiCS#4]
Hi Catalina,

I was following the steps to generate a toy dataset to play around. I did the following:

```R
library(BASiCS)
```
>    BASiCS (v0.5.7) has been extended to cover differential expression
    analyses (mean and over-dispersion), as described in
    http://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0930-3.
    New vignette file is in preparation. In the meantime, please refer
    to the supplementary files provided in the link for the code
    required to use the new functionalities. If you have any doubts,
    please contact catalina.vallejos@mrc-bsu.cam.ac.uk.

```R
Data = makeExampleBASiCS_Data(WithBatch = FALSE)
```
> An object of class BASiCS_Data
 Dataset contains 120 genes (100 biological and 20 technical) and 20 cells.
 Elements (slots): Counts, Tech, SpikeInput, GeneNames and BatchInfo.
 The data contains 1 batch.

> NOTICE: BASiCS requires a pre-filtered dataset
    - You must remove poor quality cells before creating the BASiCS data object
    - We recommend to pre-filter very lowly expressed transcripts before creating the object.
      Inclusion criteria may vary for each data. For example, remove transcripts
          - with very low total counts across of all of the samples
          - that are only expressed in a few cells
            (by default genes expressed in only 1 cell are not accepted)
          - with very low total counts across the samples where the transcript is expressed

 > BASiCS_Filter can be used for this purpose

Is this NOTICE expected for the generate toy dataset? If so I would suggest saying that on the documentation right after the line and showing the resolution. Sorry for being naive on that (just learning your stuff), but as a new user it might surprises him/her that the quick start example already gives a notice (i.e. a complain) and no quick resolution is presented.

Danilo =)

**Comment by catavallejos** [comment]
Hi Danilo,

I put that notification whenever creating a new BASiCS_Data object. However, I do agree it's not required when creating the toy example (for which no filter is required). That's quite easy to change by replacing the usage of newBASiCS_Data by the following 

Line 328. Data = new("BASiCS_Data", Counts = Counts.sim, Tech = ifelse(1:q > q.bio, T, F), SpikeInput = SpikeInfo[,2], GeneNames = paste0("Gene", 1:q), BatchInfo = BatchInfo = rep(1,20))

Line 332. Data = new("BASiCS_Data", Counts = Counts.sim, Tech = ifelse(1:q > q.bio, T, F), SpikeInput = SpikeInfo[,2], GeneNames = paste0("Gene", 1:q), BatchInfo = c(rep(1,10), rep(2,10)))

Happy to change it myself once you are not working on the R file. 

Cata

**Comment by Horta** [comment]
Don't worry about pushing new stuff to the master. I will merge into my stuff whatever you have pushed to yours before submitting a new pull request....

**Comment by catavallejos** [comment]
Done! I also updated the cpp file with the changes I was doing. I still need to do some work on that, but the 'muUpdate' function is ready.
