### ISSUE TITLE
Improve ease of use with existing SingleCellExperiment objects

### ISSUE THREAD

**Issue by jenzopr** [catavallejos/BASiCS#54]
Hi!

I'd like to use BASiCS with existing `SingleCellExperiment` objects and followed the [Input preparation guideline](https://github.com/catavallejos/BASiCS/wiki/2.-Input-preparation) from the Wiki to make them ready for `BASiCS_MCMC`. 

Here are my findings along the journey making it possible:
* The [Input preparation guideline](https://github.com/catavallejos/BASiCS/wiki/2.-Input-preparation) states that `BatchInfo` should be in `metadata(object)`, however, `HiddenBASiCS_MCMC_InputCheck.R` looks in `colData` (see [here](https://github.com/catavallejos/BASiCS/blob/044f344e0876c0a2d1174e46b790fc4596f391b4/R/HiddenBASiCS_MCMC_InputCheck.R#L10))
* During the `HiddenChecksBASiCS_Data` check (see [here](https://github.com/catavallejos/BASiCS/blob/044f344e0876c0a2d1174e46b790fc4596f391b4/R/HiddenBASiCS_MCMC_InputCheck.R#L13)), the `assay` function is _sloppily_ called without an explicit `assayName`, with the effect that the first assay is chosen. In my case, the first assay is called `abundance`, but it does not contain counts. The assay that contains counts is called `counts`. I hope it will be possible to pass the `assayName` that should be used by BASiCS to `BASiCS_MCMC`, just like its the case for many functions from [scater](http://bioconductor.org/packages/release/bioc/html/scater.html) (often called `exprs_values`). 
* The [Input preparation guideline](https://github.com/catavallejos/BASiCS/wiki/2.-Input-preparation) states that colData should contain a logical `Tech` variable indicating biological/technical genes. However, [here](https://github.com/catavallejos/BASiCS/blob/044f344e0876c0a2d1174e46b790fc4596f391b4/R/HiddenBASiCS_MCMC_InputCheck.R#L13) the return value from `isSpike()` is used. This does not need to correspond to `colData(Data)$Tech`. I had to circumvent by setting `isSpike(object, "test") <- FALSE`. 
* For `SingleCellExperiment` objects without SpikeIns, the check for a valid `SpikeInput` [here](https://github.com/catavallejos/BASiCS/blob/044f344e0876c0a2d1174e46b790fc4596f391b4/R/HiddenChecksBASiCS_Data.R#L19) needs to be tricked by setting `metadata(object) <- list(SpikeInput = 1)`, otherwise the tests will fail. I think that in case of `WithSpikes = FALSE`, `SpikeInput` does not need to be validated at all.

Please don't get me wrong: BASiCS is a great tool - but it would be even cooler if it would be easy to use :blush:

Best and hope this might help others in the future, or serve you, Cata and Nils, for further improvement of usability.
Jens

Edit: Let me know if you support a PR with the proposed changes - I'm happy to jump in.

**Comment by catavallejos** [comment]
Hi Jens,

Nice to hear from you! Constructive criticism is always welcome and it's definitely on our best interests to make the use of BASiCS as easy as possible. Please go ahead and submit a PR if you have the time to implement any of your suggested changes. That would be much appreciated!

Best

Cata

**Comment by nilseling** [comment]
Hi Jens,
thanks for pointing these things out! All of this is very useful. I'm currently rewriting parts of BASiCS to make it user-friendly.  Especially the non-spike case is still a bit confusing and I will remove some checks so that you can directly run the MCMC on the SCE object.
Keep us updated if you find more things in BASiCS that are a bit strange or annoying from a users perspective.
Best,
Nils

**Comment by jenzopr** [comment]
Great to hear, Nils! Thanks a lot for your effort!
I'm a bit occupied these days and haven't had the chance to prepare a PR as promised 😿 
Best,
Jens

**Comment by jenzopr** [comment]
Hi Cata & Nils,

I saw that you recently worked a lot on the `HiddenChecksBASiCS_Data` function and resolved all of the issues mentioned above. Major modifications of my `SingleCellExperiment` object were not necessary any more with version 1.3.18 - great work, thanks a lot! 

See you soon in CSH ☺️

**Comment by nilseling** [comment]
Hi Jens,
yes, I wanted to close this issue once I extended the Wiki and vignette. But good that you remind me to finish these parts :)
See you soon!
Best,
Nils

**Comment by catavallejos** [comment]
Hi Jens,

Excellent! I am glad it's all resolved now (credits to Nils for that!).

Looking forward to seeing you again at CSH!

Best,

Cata
