### ISSUE TITLE
Look for R:: in C++ code

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#63]

**Comment by catavallejos** [comment]
Hint: look at `RcppZiggurat` package

**Comment by Alanocallaghan** [comment]
Changing these functions seems to make the sampler mix poorly for theta. Looking at the distributions produced by these functions, I'm not really sure why.

```r
hists <- function(shape, rate, n = 10000) {
    rcppgamma <- callRcpprgamma(n, shape, rate)
    rgamma <- callRrgamma(n, shape, rate)
    stdgamma <- callstdgamma(n, shape, rate)
    par(mfrow = c(3, 1))
    set.seed(42)
    hist(rcppgamma, breaks="FD")
    set.seed(42)
    hist(rgamma, breaks="FD")
    set.seed(42)
    hist(stdgamma, breaks="FD")
}
hists(19, 0.5)
```
![gammas](https://user-images.githubusercontent.com/10779688/53631640-e6247800-3c0a-11e9-8408-7d197e3a10f5.png)

**Comment by catavallejos** [comment]
Hi Alan,

Can you try the following?

```
hists <- function(shape, rate, n = 10000) {
    rcppgamma <- callRcpprgamma(n, shape, rate)
    rgamma <- callRrgamma(n, shape, rate)
    stdgamma <- callstdgamma(n, shape, 1/rate)
    par(mfrow = c(3, 1))
    set.seed(42)
    hist(rcppgamma, breaks="FD")
    set.seed(42)
    hist(rgamma, breaks="FD")
    set.seed(42)
    hist(stdgamma, breaks="FD")
}
hists(19, 0.5)
```

Perhaps the std library uses the shape & scale parametrisation (rather than shape & rate)?

Best

Cata

**Comment by Alanocallaghan** [comment]
You're correct actually, it does use shape and scale parameterisation (see [docs](http://www.cplusplus.com/reference/random/gamma_distribution/)).

Though it seems that `Rcpp::rgamma` and `R::rgamma` also use this parameterisation, though (see [docs](http://dirk.eddelbuettel.com/code/rcpp/html/namespaceRcpp.html#abe5c752e70e1913b58df2d1f01eadb9e)) and [here](https://stackoverflow.com/questions/23439475/density-gamma-in-rcpp-and-r)

**Comment by catavallejos** [comment]
OK - let's discuss this later. I will be at the office all day.

**Comment by Alanocallaghan** [comment]
Great, I'm working from home until lunchtime. BTW, the code below shows that the parameterisations are all (shape, scale) except the R stats::rgamma.

```r
hists <- function(shape, rate, n = 10000) { 
  rcppgamma <- callRcpprgamma(n, shape, 1/rate) 
  rgamma <- callRrgamma(n, shape, 1/rate) 
  stdgamma <- callstdgamma(n, shape, 1/rate) 
  basergamma <- rgamma(n, shape=shape, rate=rate)
  par(mfrow = c(4, 1)) 
  set.seed(42) 
  hist(rcppgamma, breaks="FD") 
  set.seed(42) 
  hist(rgamma, breaks="FD") 
  set.seed(42) 
  hist(stdgamma, breaks="FD") 
  set.seed(42) 
  hist(basergamma, breaks="FD") 
} 
hists(19, 0.5)
```

**Comment by Alanocallaghan** [comment]
I got this working as discussed on Friday. Mixing now seems quite fine so it must have been a random seed issue. 

The question remains as to how the tests which rely on exact parameter values should be updated.

It probably be good in future to be able to test the individual components of the chain (eg, proposals, acceptance, etc), probably with #68

**Comment by Alanocallaghan** [comment]
R heavily recommends against using std RNG in native code so this isn't a good idea, and I don't think there are any other obvious functions to replace
