### ISSUE TITLE
Clarify and maintain code style

### ISSUE THREAD

**Issue by Alanocallaghan** [catavallejos/BASiCS#67]
The code style is fairly inconsistent across files in terms of indentation, spacing, brace placement etc. The easiest way to resolve is to agree on a style guide (eg, [google's for C++](https://github.com/google/styleguide/tree/gh-pages/cpplint) and [tidyverse's for R](http://style.tidyverse.org)) and periodically apply a code styling tool (eg, [Astyle](http://astyle.sourceforge.net/) for C++ or [styler](https://github.com/r-lib/styler/) for R).

**Comment by catavallejos** [comment]
Absolutely agreed!

**Comment by catavallejos** [comment]
Agreed to format according to tydiverse style, for example:

```
do_something_very_complicated(
  something = "that",
  requires = many,
  arguments = "some of which may be long"
)
```
