### ISSUE TITLE
incompatible matrix dimensions: 9x1 and 8x1 from HiddenBASiCS_MCMCcppRegNoSpikes

### ISSUE THREAD

**Issue by kristinazuza** [catavallejos/BASiCS#75]
Hi All, 
I am very new to Bioconductor, R in general,  but came to a point where I want to do a DE analysis among groups in my scRNAseq data set by using BASiCS.
I am dealing with No Spikes data set and therefore using colData(sce_object)$BatchInfo. 
Main issue I have currently is with running BASiCS_MCMC with error appearing :
```
 Error in HiddenBASiCS_MCMCcppRegNoSpikes(N, Thin, Burn, as.matrix(counts(Data))[!spikes,  : 
  copy into submatrix: incompatible matrix dimensions: 9x1 and 8x1.
```

This is the code I am trying to run the BASICS_MCMC:
```
chainNR <- BASiCS_MCMC(sce, 
                       WithSpikes = FALSE, 
                       N = 1000, Thin = 10,
                       Burn = 500, 
                       Regression = TRUE)
```
Using R version 3.5.2
Could you help me with it, please?

Cheers, 
Kristina

**Comment by catavallejos** [comment]
Hi Kristina,

Thanks for getting in touch. Could you please try again after re-installing BASiCS from Github?:

```
devtools::install_github("catavallejos/BASiCS", ref = "RELEASE_3_8")
```

Please do let me know if that solves the issue.

Best

Cata

**Comment by kristinazuza** [comment]
Hi Cata, 
thank you for such a fast response!

I have just tried it. Installed BASiCS from Github and it is still showing the same error (copying it with more details):
``Running no spikes BASiCS sampler (regression case) ... 

error: copy into submatrix: incompatible matrix dimensions: 9x1 and 8x1
Error in HiddenBASiCS_MCMCcppRegNoSpikes(N, Thin, Burn, as.matrix(counts(Data))[!spikes,  : 
  copy into submatrix: incompatible matrix dimensions: 9x1 and 8x1
In addition: Warning message:
In HiddenChecksBASiCS_Data(counts(Data), Spikes, metadata(Data)$SpikeInput,  :
  Some genes have zero counts across all cells. 
If comparing 2 groups, use `PriorDelta = 'log-normal' in BASiCS_MCMC.
If not, please remove those genes.

Timing stopped at: 0.02 0 0.02``

If you have any other clue, please let me know at any time. 

Best, 
Kristina

**Comment by nilseling** [comment]
Hi Kristina,

I have noticed that bug yesterday and proposed a fix and additional checks in the RELEASE_3_8 branch. In my case the error came from having spaces in the batch names. Is this also the case for you? Could you let me know the results of: 

unique(colData(sce_object)$BatchInfo)

Could you try changing the batch names into something more generic like "1" and "2"? Or alternatively, change the BatchInfo slot into a factor: 

colData(sce_object)$BatchInfo <- as.factor(colData(sce_object)$BatchInfo)

Of course, there could be something that I didn't think of.

Best and sorry for the inconvenience,

Nils

**Comment by kristinazuza** [comment]
Hi Nils, 

thank you for reply.
so I have run : 
````
test <- colData(sce_object)
test$BatchInfo <- test$processing
#processing is a batch column in my sce_object
colData(sce_object) <- test

##filtering low counts
Filter <- BASiCS_Filter(counts(sce_object))

sce_object <- sce_object[rownames(Filter$Counts),]

counts(sce_object) <- Filter$Counts

sce_object_new<- basics[,colData(sce_object)$category == "NR"]
#sce_object_new: to contain only 1 group of cells=NR to perform BASICS_MCMC

counts(sce_object_new) <- round(counts(sce_object_newr))
unique(colData(sce_object_new)$BatchInfo)
##output: 
[1] b1 b2 b3 b4 b5 b6 b7 b8 b9
Levels: b1 b2 b3 b4 b5 b6 b7 b8 b9

chainNR <- BASiCS_MCMC(sce_object_new 
+                        WithSpikes = FALSE, 
+                        N = 1000, Thin = 10,
+                        Burn = 500, 
+                        Regression = TRUE)
Running no spikes BASiCS sampler (regression case) ... 

##
error: copy into submatrix: incompatible matrix dimensions: 9x1 and 8x1
Error in HiddenBASiCS_MCMCcppRegNoSpikes(N, Thin, Burn, as.matrix(counts(Data))[!spikes,  : 
  copy into submatrix: incompatible matrix dimensions: 9x1 and 8x1
In addition: Warning message:
In HiddenChecksBASiCS_Data(counts(Data), Spikes, metadata(Data)$SpikeInput,  :
  Some genes have zero counts across all cells. 
If comparing 2 groups, use `PriorDelta = 'log-normal' in BASiCS_MCMC.
If not, please remove those genes.

Timing stopped at: 0 0.03 0.04

``
Sorry for the long code, but I might also be doing something wrong and then bothering you for nothing. 
Thank you once again.
Best,
Kristina

**Comment by nilseling** [comment]
Hmm, I don't see anything that can cause this. I will have to think about this and test a few things. Let me get back to you next week.
Sorry for that!
Best,
Nils

**Comment by nilseling** [comment]
Hi Kristina,

I think I fixed the bug now. Could you please reinstall BASiCS:

devtools::install_github("catavallejos/BASiCS", ref = "RELEASE_3_8")

Run the code again and let me know if that works. And on a different note: it's better if you run the sampler for more than just 1000 iterations. Depending on how many cells you have, you should run the sampler for at least 20,000 iterations. Just to make sure that it converges :)
Best,
Nils

**Comment by kristinazuza** [comment]
Hi Nils, 

thank you for working on it!
I have reinstalled the BASiCS and now it seems to be running, it is not showing the previous error anymore,  but I have  a different problem now. This is what I get when I run the code:

`Running no spikes BASiCS sampler (regression case) ... 

-----------------------------------------------------
MCMC sampler has been started: 1000 iterations to go.
-----------------------------------------------------
Error when updating delta14702`

Regarding the number of iterations.. my data set consists of 96 cells and if I understood it correctly MCMC chain has to be created for each group one wants to compare individually. Therefore I am running it for cca 30 cells. Could it be that the number is too little?
Thank you once again.

Best, 
Kristina

**Comment by nilseling** [comment]
Hi Kristina,

good that the first bug was fixed :)
For your current problem: we have seen that happening when there are a lot of non- or lowly expressed genes present in the dataset. Did you remove lowly expressed genes across all cells? 
Best,
Nils

**Comment by kristinazuza** [comment]
yes! That is great! :D
I have removed the non-expressed genes prior to running the code and I am using here BASiCS_Filter filtering  criteria on the sce object.

Best, 
Kristina

**Comment by catavallejos** [comment]
Excellent! I will close this issue now, but please let us know if you have any other issues.
