### ISSUE TITLE
Fix imports to avoid unnecessary load

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#81]
E.g. ggplot2 -> import individual function rather than the whole package

**Comment by catavallejos** [comment]
`import ggplot2` has been removed from NAMESPACE, replaced by imports to individual functions. Check whether anything is missing.

**Comment by catavallejos** [comment]
@nilseling can you check `BASiCS_showFit`?

**Comment by Alanocallaghan** [comment]
If using `ggplot::foo` we don't need `#' @importFrom ggplot foo`
