### ISSUE TITLE
Installation issue on R 3.3.2, Windows 7

### ISSUE THREAD

**Issue by dvzhukov** [catavallejos/BASiCS#9]
Excited to try the BASiCS package (but am a total R novice)!
Here's where I'm getting stuck:

`> devtools::install_github("catavallejos/BASiCS", build_vignettes = TRUE)`

`Downloading GitHub repo catavallejos/BASiCS@master`
`from URL https://api.github.com/repos/catavallejos/BASiCS/zipball/master`
`running command '"C:/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 127`

`Error in if (!file.exists(path)) { : argument is of length zero`

Thanks in advance for any help!

**Comment by dvzhukov** [comment]
Ok, I did some more digging around and was able to solve this issue. In case others run into it, here is what I had to do:

1. Install `Rtools` by following these steps (quoting from [here](http://stackoverflow.com/a/29480538)):
       1.  Install `Rtools` from [HERE](https://cran.r-project.org/bin/windows/Rtools/).
       2.  Locate the folder that `Rtools` is installed. In my case it is at `C:\Rtools`.
       3.  Add `C:\Rtools\bin` path to the system path.
Adding `C:\Rtools\bin` to the system path:
       1,  Go to `Control Panel >> System and Security >> System`
       2.  Go to `Advanced System Settings`
       3.  Open `Advanced` tab
       4.  Click `Environmental Variables...` button
       5.  Select `Path` variable and click `Edit` button
       6.  If there is nothing as a "Variable Value" you can simply write `C:\Rtools\bin`. If there is already a value, then add `;C:\Rtools\bin` to the end of it.
       7.  Click OK, OK...
       8.  Restart R, it should work.

2. I also had to install `testthat` and `colorspace` packages:
- `devtools::install_github("hadley/testthat")`
- `install.packages("colorspace")`

Hopefully this saves you folks a little time!

**Comment by catavallejos** [comment]
Many thanks for posting the solution! I will add these suggestions to the troubleshooting section in the repo.
