### ISSUE TITLE
Fix dependency to KernSmooth

### ISSUE THREAD

**Issue by catavallejos** [catavallejos/BASiCS#91]
> smoothScatter produces a smoothed version of a scatter plot. Two dimensional (kernel density) smoothing is performed by bkde2D from package KernSmooth. See the examples for how to use this function together with pairs.

Maybe change by another type of plot? or add explicit import to `bkde2D`?

**Comment by Alanocallaghan** [comment]
It's slightly horrible that one of the included packages relies on a non-included package for some of its functionality... Could use `geom_hex` again as with other figures, or as you say include the dependency and import one function to stop CMD check from complaining.

**Comment by catavallejos** [comment]
Indeed! For now, I added an explicit import. However, I am keen to change to ggplot2 (although I wouldn't say it's a high priority for this release)

**Comment by Alanocallaghan** [comment]
We no longer use kernsmooth so this should be removed. Also the documentation for showFit says we use kernsmooth but we use hexbin still.

Could switch to use ggpointdensity instead, but hexbin comes with ggplot2 so fewer dependencies.

**Comment by catavallejos** [comment]
I like the idea of moving to `ggpointdensity`, best to reduce the number of dependencies whenever possible.
